"""empty message

Revision ID: 036c81c4b5d1
Revises: 7b88a1ecd9f5
Create Date: 2021-05-30 00:12:33.589621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '036c81c4b5d1'
down_revision = '7b88a1ecd9f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shoppingcart')
    op.add_column('orders', sa.Column('customer', sa.Integer(), nullable=False))
    op.drop_index('name', table_name='orders')
    op.drop_index('name_2', table_name='orders')
    op.create_foreign_key(None, 'orders', 'customers', ['customer'], ['id'])
    op.drop_column('orders', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('name', mysql.VARCHAR(length=150), nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_index('name_2', 'orders', ['name'], unique=False)
    op.create_index('name', 'orders', ['name'], unique=False)
    op.drop_column('orders', 'customer')
    op.create_table('shoppingcart',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
