"""empty message

Revision ID: 09e2f03ce687
Revises: 225261f97394
Create Date: 2021-05-14 15:19:24.651809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e2f03ce687'
down_revision = '225261f97394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'date')
    # ### end Alembic commands ###
