"""empty message

Revision ID: 15884f29907a
Revises: 64514021421d
Create Date: 2021-07-01 01:27:40.259522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15884f29907a'
down_revision = '64514021421d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'employees', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'department_id')
    # ### end Alembic commands ###
