"""empty message

Revision ID: 1ce3c9475631
Revises: 94fa8c65d3a3
Create Date: 2021-05-16 20:06:53.198346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce3c9475631'
down_revision = '94fa8c65d3a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('descrip', sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'descrip')
    # ### end Alembic commands ###
