"""empty message

Revision ID: 225261f97394
Revises: dfe98833ef85
Create Date: 2021-05-14 15:15:28.941793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '225261f97394'
down_revision = 'dfe98833ef85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='stocking_clerks')
    op.drop_index('email_2', table_name='stocking_clerks')
    op.drop_index('username', table_name='stocking_clerks')
    op.drop_index('username_2', table_name='stocking_clerks')
    op.drop_table('stocking_clerks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocking_clerks',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username_2', 'stocking_clerks', ['username'], unique=False)
    op.create_index('username', 'stocking_clerks', ['username'], unique=False)
    op.create_index('email_2', 'stocking_clerks', ['email'], unique=False)
    op.create_index('email', 'stocking_clerks', ['email'], unique=False)
    # ### end Alembic commands ###
