"""empty message

Revision ID: 3854f0fac56c
Revises: 036c81c4b5d1
Create Date: 2021-05-30 00:23:37.476954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3854f0fac56c'
down_revision = '036c81c4b5d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('description', mysql.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
