"""empty message

Revision ID: 64514021421d
Revises: b293b9a9df9d
Create Date: 2021-07-01 00:58:01.282597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64514021421d'
down_revision = 'b293b9a9df9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'department')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department', mysql.VARCHAR(length=150), nullable=True))
    # ### end Alembic commands ###
