"""empty message

Revision ID: 666483d87d64
Revises: 16d9ee254245
Create Date: 2021-07-01 01:58:17.930579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '666483d87d64'
down_revision = '16d9ee254245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('dept', sa.String(length=60), nullable=True))
    op.drop_index('department', table_name='departments')
    op.create_unique_constraint(None, 'departments', ['dept'])
    op.drop_column('departments', 'department')
    op.alter_column('employees', 'first_name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('employees', 'last_name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('employees', 'email',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('employees', 'password',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('employees', 'department_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index('deparment_id_idx', table_name='employees')
    op.create_foreign_key(None, 'employees', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_index('deparment_id_idx', 'employees', ['department_id'], unique=False)
    op.alter_column('employees', 'department_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('employees', 'password',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('employees', 'email',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('employees', 'last_name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('employees', 'first_name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.add_column('departments', sa.Column('department', mysql.VARCHAR(length=60), nullable=False))
    op.drop_constraint(None, 'departments', type_='unique')
    op.create_index('department', 'departments', ['department'], unique=False)
    op.drop_column('departments', 'dept')
    # ### end Alembic commands ###
