"""empty message

Revision ID: 6dbe821e1b42
Revises: a74a25b1b3e3
Create Date: 2021-06-29 20:21:09.920856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dbe821e1b42'
down_revision = 'a74a25b1b3e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offlineorders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('contact', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('zipcode', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact'),
    sa.UniqueConstraint('contact'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_offlineorders_first_name'), 'offlineorders', ['first_name'], unique=False)
    op.create_index(op.f('ix_offlineorders_last_name'), 'offlineorders', ['last_name'], unique=False)
    op.create_foreign_key(None, 'employees', 'departments', ['department'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_index(op.f('ix_offlineorders_last_name'), table_name='offlineorders')
    op.drop_index(op.f('ix_offlineorders_first_name'), table_name='offlineorders')
    op.drop_table('offlineorders')
    # ### end Alembic commands ###
