"""empty message

Revision ID: 7841b5e9928e
Revises: 15a67252511d
Create Date: 2021-06-29 20:24:42.507765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7841b5e9928e'
down_revision = '15a67252511d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'employees', 'departments', ['department'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    # ### end Alembic commands ###
