"""empty message

Revision ID: 7b88a1ecd9f5
Revises: 9f7fbe64d601
Create Date: 2021-05-29 13:11:10.299528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b88a1ecd9f5'
down_revision = '9f7fbe64d601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shoppingcart')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shoppingcart',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
