"""empty message

Revision ID: 838b4fedee58
Revises: 1ce3c9475631
Create Date: 2021-05-16 20:07:32.982048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '838b4fedee58'
down_revision = '1ce3c9475631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'descrip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('descrip', mysql.VARCHAR(length=1000), nullable=False))
    # ### end Alembic commands ###
