"""empty message

Revision ID: 94fa8c65d3a3
Revises: c197541483f7
Create Date: 2021-05-16 20:02:05.791732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94fa8c65d3a3'
down_revision = 'c197541483f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand_id', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_constraint('products_ibfk_1', 'products', type_='foreignkey')
    op.drop_constraint('products_ibfk_2', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'])
    op.drop_column('products', 'category')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('category', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_ibfk_2', 'products', 'brands', ['brand'], ['id'])
    op.create_foreign_key('products_ibfk_1', 'products', 'categories', ['category'], ['id'])
    op.drop_column('products', 'category_id')
    op.drop_column('products', 'brand_id')
    # ### end Alembic commands ###
