"""empty message

Revision ID: 99b06c4ec9d0
Revises: 15884f29907a
Create Date: 2021-07-01 01:28:52.135709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99b06c4ec9d0'
down_revision = '15884f29907a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'employees', 'departments', ['department'], ['id'])
    op.drop_column('employees', 'department_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'department')
    # ### end Alembic commands ###
