"""empty message

Revision ID: 99db51c0d9c5
Revises: e1f404d81fdd
Create Date: 2021-06-04 20:51:26.154018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99db51c0d9c5'
down_revision = 'e1f404d81fdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'departments', ['dept'])
    op.add_column('employees', sa.Column('department', sa.Integer(), nullable=True))
    op.alter_column('employees', 'first_name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('employees', 'last_name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('employees', 'email',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('employees', 'password',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.drop_index('password_UNIQUE', table_name='employees')
    op.create_foreign_key(None, 'employees', 'departments', ['department'], ['id'])
    op.alter_column('products', 'discount',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('products', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('products', 'discount',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_index('password_UNIQUE', 'employees', ['password'], unique=False)
    op.alter_column('employees', 'password',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('employees', 'email',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('employees', 'last_name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('employees', 'first_name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.drop_column('employees', 'department')
    op.drop_constraint(None, 'departments', type_='unique')
    # ### end Alembic commands ###
