"""empty message

Revision ID: ad76c821ab86
Revises: b16753c0eeeb
Create Date: 2021-05-15 14:55:20.976865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad76c821ab86'
down_revision = 'b16753c0eeeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('password', sa.String(length=150), nullable=True))
    op.drop_column('employees', 'password_hash')
    op.add_column('products', sa.Column('image', sa.String(length=150), nullable=False))
    op.alter_column('products', 'name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.drop_index('price', table_name='products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('price', 'products', ['price'], unique=False)
    op.alter_column('products', 'price',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.drop_column('products', 'image')
    op.add_column('employees', sa.Column('password_hash', mysql.VARCHAR(length=150), nullable=True))
    op.drop_column('employees', 'password')
    # ### end Alembic commands ###
