"""empty message

Revision ID: b293b9a9df9d
Revises: e9e0d966d68e
Create Date: 2021-07-01 00:51:33.243604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b293b9a9df9d'
down_revision = 'e9e0d966d68e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('contact', table_name='offlinecustomers')
    op.drop_index('contact_2', table_name='offlinecustomers')
    op.drop_index('email', table_name='offlinecustomers')
    op.drop_index('email_2', table_name='offlinecustomers')
    op.drop_index('ix_offlineorders_first_name', table_name='offlinecustomers')
    op.drop_index('ix_offlineorders_last_name', table_name='offlinecustomers')
    op.drop_table('offlinecustomers')
    op.create_foreign_key(None, 'employees', 'departments', ['department'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_table('offlinecustomers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('contact', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('zipcode', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_offlineorders_last_name', 'offlinecustomers', ['last_name'], unique=False)
    op.create_index('ix_offlineorders_first_name', 'offlinecustomers', ['first_name'], unique=False)
    op.create_index('email_2', 'offlinecustomers', ['email'], unique=False)
    op.create_index('email', 'offlinecustomers', ['email'], unique=False)
    op.create_index('contact_2', 'offlinecustomers', ['contact'], unique=False)
    op.create_index('contact', 'offlinecustomers', ['contact'], unique=False)
    # ### end Alembic commands ###
