"""empty message

Revision ID: c197541483f7
Revises: cd2be3991084
Create Date: 2021-05-16 19:42:05.268970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c197541483f7'
down_revision = 'cd2be3991084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('category', sa.Integer(), nullable=False))
    op.drop_constraint('products_ibfk_1', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category'], ['id'])
    op.create_foreign_key(None, 'products', 'brands', ['brand'], ['id'])
    op.drop_column('products', 'brand_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_ibfk_1', 'products', 'brands', ['brand_id'], ['id'])
    op.drop_column('products', 'category')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###
