"""empty message

Revision ID: cd2be3991084
Revises: 0aeffbb31b98
Create Date: 2021-05-16 15:43:00.747670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd2be3991084'
down_revision = '0aeffbb31b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('color', sa.Text(), nullable=False))
    op.add_column('products', sa.Column('image_1', sa.String(length=150), nullable=False))
    op.add_column('products', sa.Column('image_2', sa.String(length=150), nullable=False))
    op.add_column('products', sa.Column('image_3', sa.String(length=150), nullable=False))
    op.add_column('products', sa.Column('brand_id', sa.Integer(), nullable=False))
    op.alter_column('products', 'description',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'])
    op.drop_column('products', 'image')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', mysql.VARCHAR(length=150), nullable=True))
    op.add_column('products', sa.Column('image', mysql.VARCHAR(length=150), nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.alter_column('products', 'description',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.drop_column('products', 'brand_id')
    op.drop_column('products', 'image_3')
    op.drop_column('products', 'image_2')
    op.drop_column('products', 'image_1')
    op.drop_column('products', 'color')
    op.drop_column('products', 'discount')
    # ### end Alembic commands ###
