"""empty message

Revision ID: e355897a1fb5
Revises: 943f94e7e42c
Create Date: 2021-05-14 20:06:41.463892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e355897a1fb5'
down_revision = '943f94e7e42c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customers_ibfk_1', 'customers', type_='foreignkey')
    op.drop_column('customers', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('customers_ibfk_1', 'customers', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
