"""empty message

Revision ID: e9e0d966d68e
Revises: 7841b5e9928e
Create Date: 2021-06-29 20:28:24.489165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9e0d966d68e'
down_revision = '7841b5e9928e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('contact', table_name='offlineorders')
    op.drop_index('contact_2', table_name='offlineorders')
    op.drop_index('email', table_name='offlineorders')
    op.drop_index('email_2', table_name='offlineorders')
    op.drop_index('ix_offlineorders_first_name', table_name='offlineorders')
    op.drop_index('ix_offlineorders_last_name', table_name='offlineorders')
    op.drop_table('offlineorders')
    op.create_foreign_key(None, 'employees', 'departments', ['department'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_table('offlineorders',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('contact', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('zipcode', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_offlineorders_last_name', 'offlineorders', ['last_name'], unique=False)
    op.create_index('ix_offlineorders_first_name', 'offlineorders', ['first_name'], unique=False)
    op.create_index('email_2', 'offlineorders', ['email'], unique=False)
    op.create_index('email', 'offlineorders', ['email'], unique=False)
    op.create_index('contact_2', 'offlineorders', ['contact'], unique=False)
    op.create_index('contact', 'offlineorders', ['contact'], unique=False)
    # ### end Alembic commands ###
