"""empty message

Revision ID: ed0ad0ae7f2c
Revises: cebf62c9cdf4
Create Date: 2021-05-16 01:25:30.526138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed0ad0ae7f2c'
down_revision = 'cebf62c9cdf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'first_name',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('customers', 'last_name',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('customers', 'email',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('customers', 'username',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('customers', 'password',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.drop_constraint('employees_ibfk_1', 'employees', type_='foreignkey')
    op.drop_column('employees', 'department_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('employees_ibfk_1', 'employees', 'departments', ['department_id'], ['id'])
    op.alter_column('customers', 'password',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('customers', 'username',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('customers', 'email',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.alter_column('customers', 'last_name',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.alter_column('customers', 'first_name',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    # ### end Alembic commands ###
