"""empty message

Revision ID: f3e260660cb2
Revises: 838b4fedee58
Create Date: 2021-05-18 14:30:17.441587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3e260660cb2'
down_revision = '838b4fedee58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'name',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.alter_column('departments', 'description',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.drop_column('products', 'image_3')
    op.drop_column('products', 'image_2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_2', mysql.VARCHAR(length=150), nullable=False))
    op.add_column('products', sa.Column('image_3', mysql.VARCHAR(length=150), nullable=False))
    op.alter_column('departments', 'description',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('departments', 'name',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    # ### end Alembic commands ###
